<?php
/** Debug Tool D005 — Mailbox IMAP/SMTP diagnostics. Secret-safe. */
@session_start();
require_once __DIR__ . '/../../../config.php';
require_once __DIR__ . '/../../../includes/functions.php';
require_once __DIR__ . '/../../../includes/encryption.php';
require_once __DIR__ . '/../../../includes/mailbox_schema.php';
require_once __DIR__ . '/../../../includes/mail/MailboxProviderFactory.php';

$sections=[]; function sec($t,$b){global $sections; if(!is_string($b))$b=json_encode($b,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES); $sections[]="=== $t ===\n".rtrim($b,"\n");}
function out(){global $sections; header('Content-Type:text/plain; charset=utf-8'); header('Cache-Control:no-store'); echo implode("\n\n",$sections)."\n"; exit;}
function val($a,$k,$d=null){return array_key_exists($k,$a)?$a[$k]:$d;}
function truthy($v){return in_array(strtolower(trim((string)$v)),['1','true','yes','on','enabled'],true);}
function setting_any(PDO $c,array $keys,$d=null){try{$ph=implode(',',array_fill(0,count($keys),'?'));$s=$c->prepare("SELECT setting_value FROM system_settings WHERE setting_key IN ($ph) ORDER BY FIELD(setting_key, $ph) LIMIT 1");$s->execute(array_merge($keys,$keys));$v=$s->fetchColumn();return $v===false?$d:$v;}catch(Throwable $e){return $d;}}
function enabled(PDO $c){foreach(['MAILBOX_DEBUG_ENABLED','mailbox_debug_enabled'] as $k){$e=getenv($k); if($e!==false&&$e!=='') return truthy($e); if(isset($_ENV[$k])&&$_ENV[$k]!=='') return truthy($_ENV[$k]); if(isset($_SERVER[$k])&&$_SERVER[$k]!=='') return truthy($_SERVER[$k]);} if(defined('MAILBOX_DEBUG_ENABLED')) return truthy(constant('MAILBOX_DEBUG_ENABLED')); return truthy(setting_any($c,['MAILBOX_DEBUG_ENABLED','mailbox_debug_enabled'],'0'));}
function can_admin(PDO $c){if(empty($_SESSION['analyst_id']))return false; $id=(int)$_SESSION['analyst_id']; try{$s=$c->prepare('SELECT 1 FROM analyst_modules WHERE analyst_id=? AND module_key="system" LIMIT 1');$s->execute([$id]); if($s->fetchColumn())return true;}catch(Throwable $e){} try{$n=$c->query('SELECT COUNT(*) FROM analyst_modules')->fetchColumn(); return ((int)$n===0); }catch(Throwable $e){return false;}}
function safe($v){ if(is_array($v)){ $o=[]; foreach($v as $k=>$x){$lk=strtolower((string)$k); if(preg_match('/password|secret|token|refresh|credential/',$lk)){$o[$k]=['present'=>($x!==null&&$x!==''),'password_present'=>($x!==null&&$x!=='')];} else $o[$k]=safe($x);} return $o;} return $v; }
function resolved($m){$enc=function($x){$x=strtolower(trim((string)$x)); return ($x===''||$x==='none'||$x==='false')?false:$x;}; return ['imap'=>['host'=>val($m,'imap_host',val($m,'imap_server','')),'port'=>(int)val($m,'imap_port',993),'protocol'=>'imap','encryption'=>$enc(val($m,'imap_encryption',false)),'validate_cert'=>false,'username'=>val($m,'imap_username',val($m,'target_mailbox','')),'password_present'=>val($m,'imap_password_encrypted','')!=='','folder'=>val($m,'imap_folder',val($m,'email_folder','INBOX'))],'smtp'=>['host'=>val($m,'smtp_host',''),'port'=>(int)val($m,'smtp_port',587),'encryption'=>$enc(val($m,'smtp_encryption','tls')),'validate_cert'=>false,'username'=>val($m,'smtp_username',val($m,'target_mailbox','')),'password_present'=>val($m,'smtp_password_encrypted','')!=='','from_address'=>val($m,'smtp_from_address',val($m,'target_mailbox',''))]];}
function trace_short(Throwable $e){return array_slice(explode("\n",$e->getTraceAsString()),0,8);}
function log_action($uid,$mid,$action,$stored,$runtime,$result,$ex=null){$dir=__DIR__.'/../../../storage/logs'; if(!is_dir($dir))@mkdir($dir,0775,true); $row=['timestamp'=>gmdate('c'),'user_id'=>$uid,'mailbox_id'=>$mid,'action_name'=>$action,'sanitized_stored_config'=>safe($stored),'sanitized_resolved_config'=>safe($runtime),'result'=>safe($result),'exception_class'=>$ex?get_class($ex):null,'exception_message'=>$ex?$ex->getMessage():null,'short_trace'=>$ex?trace_short($ex):[]]; @file_put_contents($dir.'/mailbox-debug.log',json_encode($row,JSON_UNESCAPED_SLASHES)."\n",FILE_APPEND|LOCK_EX);}
function sock_line($fp){$l=fgets($fp,4096); return $l===false?'':rtrim($l,"\r\n");}
function cmd($fp,$c){fwrite($fp,$c."\r\n"); $lines=[]; do{$l=sock_line($fp); if($l==='')break; $lines[]=$l;}while(isset($l[3])&&$l[3]==='-'); return $lines;}
function raw_imap($r,$m){$host=$r['imap']['host'];$port=$r['imap']['port'];$transport=$r['imap']['encryption']==='ssl'?'ssl://':'';$fp=@fsockopen($transport.$host,$port,$eno,$estr,10); if(!$fp)throw new RuntimeException("connect failed: $estr ($eno)"); stream_set_timeout($fp,10); $o=['banner'=>sock_line($fp)]; if($r['imap']['encryption']==='tls'){$o['starttls']=cmd($fp,'a001 STARTTLS'); if(isset($o['starttls'][0])&&str_starts_with($o['starttls'][0],'a001 OK')) stream_socket_enable_crypto($fp,true,STREAM_CRYPTO_METHOD_TLS_CLIENT);} $u=str_replace(['\\','"'],['\\\\','\\"'],$r['imap']['username']); $p=str_replace(['\\','"'],['\\\\','\\"'],(string)val($m,'imap_password_encrypted','')); $o['login']=cmd($fp,'a002 LOGIN "'.$u.'" "'.$p.'"'); $folder=str_replace(['\\','"'],['\\\\','\\"'],$r['imap']['folder']); $o['select']=cmd($fp,'a003 SELECT "'.$folder.'"'); $o['search']=cmd($fp,'a004 SEARCH ALL'); $o['logout']=cmd($fp,'a005 LOGOUT'); fclose($fp); return safe($o);}
function raw_smtp($r,$m,$send=false,$to=''){$host=$r['smtp']['host'];$port=$r['smtp']['port'];$transport=$r['smtp']['encryption']==='ssl'?'ssl://':'';$fp=@fsockopen($transport.$host,$port,$eno,$estr,10); if(!$fp)throw new RuntimeException("connect failed: $estr ($eno)"); stream_set_timeout($fp,10); $o=['banner'=>sock_line($fp),'ehlo'=>cmd($fp,'EHLO freeitsm-debug')]; if($r['smtp']['encryption']==='tls'){$o['starttls']=cmd($fp,'STARTTLS'); if(isset($o['starttls'][0])&&str_starts_with($o['starttls'][0],'220')){stream_socket_enable_crypto($fp,true,STREAM_CRYPTO_METHOD_TLS_CLIENT);$o['ehlo_after_starttls']=cmd($fp,'EHLO freeitsm-debug');}} $u=(string)$r['smtp']['username'];$p=(string)val($m,'smtp_password_encrypted',''); if($u!==''&&$p!==''){$o['auth_login_user']=cmd($fp,'AUTH LOGIN');$o['auth_login_username']=cmd($fp,base64_encode($u));$o['auth_login_password']=cmd($fp,base64_encode($p));}
 if($send){$from=(string)$r['smtp']['from_address']; $to=$to?:$from; $o['mail_from']=cmd($fp,'MAIL FROM:<'.$from.'>');$o['rcpt_to']=cmd($fp,'RCPT TO:<'.$to.'>');$o['data']=cmd($fp,'DATA');fwrite($fp,"Subject: FreeITSM SMTP debug test\r\nFrom: <$from>\r\nTo: <$to>\r\n\r\nSMTP debug test generated at ".gmdate('c').".\r\n.\r\n");$o['data_result']=[sock_line($fp)];}
 $o['quit']=cmd($fp,'QUIT'); fclose($fp); return safe($o);} 

$uid=$_SESSION['analyst_id']??null; try{$conn=connectToDatabase(); ensureTargetMailboxSchema($conn);}catch(Throwable $e){sec('DATABASE','FAILED: '.$e->getMessage()); out();}
if(!can_admin($conn)){http_response_code(403);sec('AUTH','FAIL: authenticated admin/sysadmin/devops access required (System module access).');out();}
if(!enabled($conn)){http_response_code(404);sec('DISABLED','MAILBOX_DEBUG_ENABLED is not true in environment or system_settings.');out();}
$mid=(int)($_POST['mailbox_id']??$_GET['mailbox_id']??0); $action=(string)($_POST['action']??$_GET['action']??'show_config'); $to=trim((string)($_POST['test_to']??$_GET['test_to']??''));
sec('WARNING','Debug mode exposes connection metadata. Do not enable in production except during troubleshooting. Secrets are never displayed or logged; only password_present=true/false is shown.');
if($mid<=0){sec('INPUT','Choose a mailbox.');out();}
$st=$conn->prepare('SELECT * FROM target_mailboxes WHERE id=?');$st->execute([$mid]);$stored=$st->fetch(PDO::FETCH_ASSOC); if(!$stored){sec('MAILBOX','Not found.');out();}
try{$mailbox=decryptMailboxRow($stored);}catch(Throwable $e){$mailbox=$stored;sec('DECRYPTION','Could not decrypt one or more fields: '.$e->getMessage());}
$runtime=resolved($mailbox); sec('STORED MAILBOX CONFIG',safe($stored)); sec('RESOLVED RUNTIME CONFIG',$runtime);
$res=null;$ex=null; try{switch($action){case 'show_config':$res=['ok'=>true];break;case 'raw_smtp':$res=raw_smtp($runtime,$mailbox,false);break;case 'send_smtp':$res=raw_smtp($runtime,$mailbox,true,$to);break;case 'raw_imap':$res=raw_imap($runtime,$mailbox);break;case 'webklex_test':MailboxProviderFactory::imap($mailbox)->test();$res=['connected'=>true];break;case 'list_folders':if(!class_exists('Webklex\\PHPIMAP\\ClientManager')){$autoload=__DIR__.'/../../../vendor/autoload.php'; if(is_readable($autoload)) require_once $autoload;} if(!class_exists('Webklex\\PHPIMAP\\ClientManager')) throw new RuntimeException('Composer dependency webklex/php-imap is not installed.'); $client=(new Webklex\PHPIMAP\ClientManager())->make(['host'=>$runtime['imap']['host'],'port'=>$runtime['imap']['port'],'protocol'=>'imap','encryption'=>$runtime['imap']['encryption'],'validate_cert'=>false,'username'=>$runtime['imap']['username'],'password'=>val($mailbox,'imap_password_encrypted','')]);$client->connect();$res=[];foreach($client->getFolders() as $f)$res[]=(string)$f->name;$client->disconnect();break;case 'list_messages':$c=MailboxProviderFactory::imap($mailbox);$msgs=$c->fetchUnseen(10);$c->close();$res=array_map(fn($x)=>['id'=>$x['id']??'','uid'=>$x['imap_msgno']??null,'from'=>$x['from']['emailAddress']['address']??'','subject'=>$x['subject']??'','receivedDateTime'=>$x['receivedDateTime']??''], $msgs);break;case 'intake_dry_run':$c=MailboxProviderFactory::imap($mailbox);$msgs=$c->fetchUnseen(10);$c->close();$res=['dry_run'=>true,'mutations'=>'none: no tickets created, no messages marked read/deleted/moved','messages_found'=>count($msgs),'first_10'=>array_map(fn($x)=>['id'=>$x['id']??'','uid'=>$x['imap_msgno']??null,'from'=>$x['from']['emailAddress']['address']??'','subject'=>$x['subject']??''], $msgs)];break;default:throw new InvalidArgumentException('Unknown action');}}catch(Throwable $e){$ex=$e;$res=['error'=>$e->getMessage()];}
log_action($uid,$mid,$action,safe($stored),$runtime,$res,$ex); sec('ACTION RESULT',safe($res)); if($ex)sec('EXCEPTION',['class'=>get_class($ex),'message'=>$ex->getMessage(),'short_trace'=>trace_short($ex)]); sec('LOG','Wrote sanitized entry to storage/logs/mailbox-debug.log'); out();
